site_name: Collision Detection for C++
theme:
  name: 'material'
nav:
  - Home: index.md
  - Installation:
    - With CMake: installation/install-cmake.md
  - Misc.:
    - Notes about the library: library/library-info.md